insert into public.questions(position,difficulty,max_points,question_text,options,correct_option,explanation) values
(1,'Dễ',50,'Theo bài báo cáo, đâu là tài sản KHÔNG nên được xem là đối tượng Licensing thông thường theo pháp luật Việt Nam?','{"A":"Nhãn hiệu","B":"Sáng chế","C":"Bản quyền","D":"Tên thương mại"}','D','Bài lưu ý quyền sử dụng tên thương mại và chỉ dẫn địa lý không được chuyển quyền sử dụng như các đối tượng Licensing thông thường.'),
(2,'Dễ',50,'Trong hình thức cấp phép duy nhất (Sole Licensing), bên cấp phép có quyền gì?','{"A":"Không được tiếp tục sử dụng tài sản đã cấp phép","B":"Vẫn được tự khai thác tài sản nhưng chỉ cấp phép cho một bên nhận phép trong phạm vi nhất định","C":"Có thể cấp phép cho không giới hạn đối tác","D":"Phải chuyển quyền sở hữu tài sản cho bên nhận phép"}','B','Sole Licensing chỉ có một bên nhận phép trong phạm vi xác định, nhưng bên cấp phép vẫn giữ quyền tự khai thác tài sản.'),
(3,'Dễ',50,'Một lợi ích của Licensing đối với bên nhận phép là gì?','{"A":"Không phải trả bất kỳ khoản phí nào","B":"Được sở hữu luôn tài sản trí tuệ","C":"Có thể tiếp cận tài sản trí tuệ đã có giá trị mà không phải phát triển hoàn toàn từ đầu","D":"Được tự do sử dụng tài sản ngoài phạm vi hợp đồng"}','C','Bên nhận phép có thể tận dụng thương hiệu, công nghệ hoặc nội dung đã được phát triển, từ đó rút ngắn thời gian nghiên cứu và đưa sản phẩm ra thị trường.'),
(4,'Trung bình',80,'Trước khi lựa chọn bên nhận phép, bên cấp phép nên đánh giá yếu tố nào?','{"A":"Chỉ doanh thu hiện tại của đối tác","B":"Chỉ số lượng nhân viên của đối tác","C":"Năng lực tài chính, kỹ thuật, sản xuất, phân phối, marketing và uy tín","D":"Chỉ mức độ nổi tiếng trên mạng xã hội"}','C','Báo cáo nhấn mạnh việc lựa chọn đúng đối tác ảnh hưởng trực tiếp đến hiệu quả khai thác tài sản và hình ảnh doanh nghiệp ở thị trường nước ngoài.'),
(5,'Trung bình',80,'Một doanh nghiệp muốn tự kiểm soát toàn bộ hoạt động sản xuất, marketing và phân phối tại thị trường nước ngoài. Licensing có phù hợp không?','{"A":"Có, vì Licensing mang lại mức kiểm soát cao nhất","B":"Có, vì bên nhận phép không tham gia vận hành","C":"Không, vì Licensing thường làm giảm mức độ kiểm soát trực tiếp","D":"Không, vì Licensing chỉ áp dụng trong thị trường nội địa"}','C','Bài báo cáo cho rằng khi doanh nghiệp muốn trực tiếp kiểm soát toàn bộ hoạt động ở nước ngoài thì nên cân nhắc phương thức thâm nhập có mức kiểm soát cao hơn Licensing.'),
(6,'Trung bình',80,'Vì sao ngành giải trí, phim ảnh và trò chơi phù hợp với Licensing?','{"A":"Vì các doanh nghiệp trong ngành không cần tài sản trí tuệ","B":"Vì bản quyền, nhân vật và nội dung sáng tạo có thể được cấp phép cho nhiều sản phẩm và thị trường","C":"Vì mọi sản phẩm giải trí đều bắt buộc phải nhượng quyền","D":"Vì bên cấp phép phải trực tiếp sản xuất toàn bộ sản phẩm"}','B','Báo cáo xác định bản quyền, nhân vật và nội dung sáng tạo là những tài sản có thể khai thác trên nhiều nhóm sản phẩm và nhiều thị trường.'),
(7,'Khá',120,'Trong Global Coffee Alliance, vai trò nào sau đây thuộc về Starbucks?','{"A":"Vận hành hệ thống phân phối toàn cầu của Nestlé","B":"Tìm nguồn cung, rang cà phê và quản lý thương hiệu Starbucks","C":"Sản xuất toàn bộ máy Nespresso","D":"Chuyển quyền sở hữu thương hiệu Starbucks cho Nestlé"}','B','Starbucks vẫn giữ vai trò quản lý thương hiệu và tiếp tục phụ trách những hoạt động quan trọng liên quan đến nguồn cung và rang cà phê.'),
(8,'Khá',120,'Theo thỏa thuận Starbucks – Nestlé năm 2018, nội dung nào KHÔNG thuộc phạm vi cấp phép ban đầu?','{"A":"Cà phê rang xay Starbucks","B":"Viên nén cà phê Starbucks","C":"Sản phẩm Starbucks bán bên trong cửa hàng Starbucks","D":"Cà phê hòa tan Starbucks"}','C','Thỏa thuận ban đầu không bao gồm việc bán sản phẩm bên trong các cửa hàng Starbucks và cũng không bao gồm nhóm đồ uống Ready-to-Drink.'),
(9,'Khó',160,'Điểm nào thể hiện rõ nhất thỏa thuận Starbucks – Nestlé là Licensing chứ không phải Franchising?','{"A":"Nestlé được mở cửa hàng Starbucks tại mọi quốc gia","B":"Nestlé sở hữu thương hiệu Starbucks sau khi thanh toán phí","C":"Nestlé chỉ khai thác các quyền được cấp đối với một số sản phẩm, còn hai doanh nghiệp vẫn hoạt động độc lập","D":"Nestlé phải vận hành theo toàn bộ mô hình cửa hàng Starbucks"}','C','Nestlé không vận hành hệ thống cửa hàng Starbucks và không sở hữu thương hiệu Starbucks. Nestlé chỉ được khai thác những quyền nằm trong phạm vi thỏa thuận.'),
(10,'BOSS',200,'Giả sử Nestlé muốn tự đưa một dòng sản phẩm Starbucks hoàn toàn mới vào bán bên trong các cửa hàng Starbucks. Dựa trên phạm vi thỏa thuận ban đầu năm 2018, nhận định nào hợp lý nhất?','{"A":"Nestlé được tự động thực hiện vì đã có quyền sử dụng thương hiệu Starbucks","B":"Nestlé được thực hiện miễn là sản phẩm có cà phê","C":"Nestlé không mặc nhiên có quyền vì hoạt động bên trong cửa hàng Starbucks nằm ngoài phạm vi cấp phép ban đầu","D":"Nestlé được thực hiện vì đã thanh toán 7,15 tỷ USD cho Starbucks"}','C','Được cấp quyền không đồng nghĩa được sử dụng IP ở mọi sản phẩm, kênh hay phạm vi. Thỏa thuận ban đầu đã giới hạn quyền của Nestlé đối với sản phẩm và kênh phân phối, trong đó hoạt động bán trong cửa hàng Starbucks không thuộc phạm vi đó.')
on conflict(position) do update set
  difficulty=excluded.difficulty,
  max_points=excluded.max_points,
  question_text=excluded.question_text,
  options=excluded.options,
  correct_option=excluded.correct_option,
  explanation=excluded.explanation;
